language: ruby

rvm:
  - 1.9.3
  - 2.0.0

install:
  - travis_retry bundle install
  - bundle exec berks vendor cookbooks

script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop site-cookbooks
  # - bundle exec kitchen test -l debug # too slow for TravisCI
