language: ruby

rvm:
  - 1.9.3
  - 2.0.0

install:
  - travis_retry bundle install
  - bundle exec berks install

script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
  # - bundle exec kitchen test -l debug # too slow for TravisCI
